spring:
  application:
    name: config-server
  cloud:
    config:
      server:
#默认搜索配置文件 src/main/resources
#指定本地配置文件路径
#       native:
#         search-locations:
#远程git仓库获取配置文件
#        git:
#          uri: http://git.oschina.net/didispace/config-repo-demo/
# 获取本地配置文件
  profiles:
    active: native

server:
    port: 8185
