spring:
  application:
    name: config-server
  cloud:
    config:
      server:
#默认搜索配置文件 src/main/resources
#指定本地配置文件路径
#       native:
#         search-locations:
#远程git仓库获取配置文件
        git:
          uri: https://github.com/ruihongHe/config-repo.git
          username: 18655377896@163.com
          password: 032502ds@
          search-paths: /test/
# 获取本地配置文件
#  profiles:
#    active: native

server:
    port: 8185
